# Generated by Django 4.0.4 on 2022-05-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_options_remove_user_user_email_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=128, null=True, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_dttm',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='계정 생성시간'),
        ),
    ]
